//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminCampana_2020.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RC2020Entities : DbContext
    {
        public RC2020Entities()
            : base("name=RC2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Telefono> Telefono { get; set; }
        public virtual DbSet<Colonia> Colonia { get; set; }
        public virtual DbSet<Estrategia> Estrategia { get; set; }
        public virtual DbSet<Seccion> Seccion { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<Afiliado> Afiliado { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
    }
}
