//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminCampana_2020.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int id { get; set; }
        public string strNombre { get; set; }
        public string strApellidoPaterno { get; set; }
        public string strApellidoMaterno { get; set; }
        public string strEmail { get; set; }
        public string strObservaciones { get; set; }
        public Nullable<int> idTelefono { get; set; }
        public Nullable<int> idDireccion { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Telefono Telefono { get; set; }
    }
}
